version: '3.9' # optional since v1.27.0
services:
  nginx-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

  json-backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./db.json:/backend/db.json
